### ISSUE TITLE
Replace PaserSetting.HelpWriter Throwing exception

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#82]
<a href="https://github.com/duke605"><img src="https://avatars1.githubusercontent.com/u/489996?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [duke605](https://github.com/duke605)**
_Thursday Aug 11, 2016 at 11:52 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/342_

----

There's a higher than likely chance that this is just me being a derp. But when I try to replace the HelpWriter with null or anything for that matter i get a InvalidOperationException.

The code I'm using.
`Parser.Default.Settings.HelpWriter = null;`

CommandLinePaserVersion: 2.0.275-beta

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Thursday Aug 11, 2016 at 19:26 GMT_

----

Can you post the stack trace? More than likely we fail to do a null check somewhere...

**Comment by ericnewton76** [comment]
<a href="https://github.com/duke605"><img src="https://avatars1.githubusercontent.com/u/489996?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [duke605](https://github.com/duke605)**
_Friday Aug 12, 2016 at 15:18 GMT_

----

I'm more of a java guy when it comes to stack traces so i have no idea if this little bit is what you're looking for

```
at CommandLine.Infrastructure.PopsicleSetter.Set[T](Boolean consumed, T& field, T value)
at CommandLine.ParserSettings.set_HelpWriter(TextWriter value)
at WerewolfBot.Program.Main(String[] args) in c:\users\cole\documents\visual studio 2015\Projects\WerewolfBot\WerewolfBot\Program.cs:line 20
```
