### ISSUE TITLE
Command breaks when trying to add FileInfo Option

### ISSUE THREAD

**Issue by sebasijan** [commandlineparser/commandline#827]
I have this command, which works fine in my console app

    [Verb("users")]
    internal sealed record SeedUserBaselines 
        : SeedBaselinesBase<User, UserDTO>
        , IRequest
    {
        public SeedUserBaselines(
            DateTime createdDate,
            int? fromId,
            int? toId )
            : base(
                createdDate,
                fromId,
                toId)
        {
        }
    }

SeedBaselinesBase:

    public abstract record SeedBaselinesBase<TEntity, TAuditingDTO>
        where TEntity : DomainEntity<Guid>
        where TAuditingDTO : new()
    {
        protected SeedBaselinesBase(
            DateTime createdDate,
            int? fromId,
            int? toId)
        {
            EnsureArg.IsNotDefault(createdDate, nameof(createdDate));
            if (toId.HasValue && fromId.HasValue)
            {
                EnsureArg.IsLte(fromId.Value, toId.Value, nameof(fromId));
            }

            CreatedDate = createdDate;
            FromId = fromId;
            ToId = toId;
        }

        [Option(shortName: 'c', longName: "createdDate", HelpText = "The date at which to set the EntityChanges.OccurredAt column.", Required = true)]
        public DateTime CreatedDate { get; }
        [Option(shortName: 'f', longName: "fromId", HelpText = "The Entity.Identity value to start processing from.", Required = false)]
        public int? FromId { get; }
        [Option(shortName: 't', longName: "toId", HelpText = "The Entity.Identity value to stop processing at.", Required = false)]
        public int? ToId { get; }
    }

However when I try to add an optional FileInfo param to the user command:

    [Verb("users")]
    internal sealed record SeedUserBaselines 
        : SeedBaselinesBase<User, UserDTO>
        , IRequest
    {
        public SeedUserBaselines(
            DateTime createdDate,
            int? fromId,
            int? toId,
            FileInfo? file)
            : base(
                createdDate,
                fromId,
                toId)
        {
            File = file;
        }

        [Option(shortName: 'i', longName: "inputFilePath", HelpText = "Path to the import spreadsheet.", Required = false)]
        public FileInfo? File { get; }
    }

I get this annoying error:

> System.InvalidOperationException: 'Type SeedUserBaselines appears to be immutable, but no constructor found to accept values.'

 >    at CommandLine.Core.InstanceBuilder.BuildImmutable[T](Type typeInfo, Maybe`1 factory, IEnumerable`1 specProps, IEnumerable`1 specPropsWithValue, List`1 setPropertyErrors)
   at CommandLine.Core.InstanceBuilder.<>c__DisplayClass1_0`1.<Build>b__5()
   at CommandLine.Core.InstanceBuilder.Build[T](Maybe`1 factory, Func`3 tokenizer, IEnumerable`1 arguments, StringComparer nameComparer, Boolean ignoreValueCase, CultureInfo parsingCulture, Boolean autoHelp, Boolean autoVersion, Boolean allowMultiInstance, IEnumerable`1 nonFatalErrors)
   at CommandLine.Parser.ParseArguments[T](IEnumerable`1 args)
   at MyProject.EntityChangesBaselineSeeder.Program.Main(String[] args) in C:\Users\basse\source\repos\MyProject\Program.cs:line 22
   at MyProject.Support.EntityChangesBaselineSeeder.Program.<Main>(String[] args)

when passing in these args

> -i "C:\Users\bassie\Downloads\Created Date.xlsx" -c 2022-01-01 -f 1 -t 100

Am I doing something wrong?

**Comment by sebasijan** [comment]
Found the answer in another issue, basically need to update the order of the ctor params, so that inherited args are at the end:

        public SeedUserBaselines(
            FileInfo? file,
            DateTime createdDate,
            int? fromId,
            int? toId)
            : base(
                createdDate,
                fromId,
                toId)
        {
            File = file;
        }
