### ISSUE TITLE
Getting Cursor Position in git-bash terminal fails with IOException

### ISSUE THREAD

**Issue by embix** [commandlineparser/commandline#851]
I made a repro using the sample code:

```csharp
using System;
using CommandLine;

namespace QuickStart
{
    class Program
    {
        public class Options
        {
            [Option('v', "verbose", Required = false, HelpText = "Set output to verbose messages.")]
            public bool Verbose { get; set; }

            [Option('p', "position", Required = false, HelpText = "Show current cursor position")]
            public bool Position { get; set; }
        }

        static void Main(string[] args)
        {
            Parser.Default.ParseArguments<Options>(args)
                   .WithParsed<Options>(o =>
                   {
                       if (o.Verbose)
                       {
                           Console.WriteLine($"Verbose output enabled. Current Arguments: -v {o.Verbose}");
                           Console.WriteLine("Quick Start Example! App is in Verbose mode!");
                       }
                       else
                       {
                           Console.WriteLine($"Current Arguments: -v {o.Verbose}");
                           Console.WriteLine("Quick Start Example!");
                       }

                       if(o.Position){
                           var pos = Console.GetCursorPosition();
                           Console.WriteLine($"Current Cursor Position is x={pos.Left}, y={pos.Top}");
                       }
                   });
        }
    }
}

```

In my git-bash on Windows 10 I get:

```
→ ./repro-commandlineparser.exe -p
Current Arguments: -v False
Quick Start Example!
Unhandled exception. System.IO.IOException: The handle is invalid.
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.ConsolePal.GetCursorPosition()
   at QuickStart.Program.<>c.<Main>b__1_0(Options o) in C:\git\Spikes\repro-commandlineparser\Program.cs:line 34
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at QuickStart.Program.Main(String[] args) in C:\git\Spikes\repro-commandlineparser\Program.cs:line 19
```

ENV-var TERM is set to xterm in case that matters, otherwise its a regular windows git installation with the default msys terminal.

WindowsTerminal, CMD and even WSL terminal (which tells me TERM is xterm-256color) and a _real_ xterm in WSL work fine.

```
❯ .\repro-commandlineparser.exe -p
Current Arguments: -v False
Quick Start Example!
Current Cursor Position is x=0, y=29
```

**Comment by ricardj** [comment]
Hi there,

It seems that this bug has nothing to do with the CommandLineParser library.

Here is the line crashing in GitBash whether or not CommandLineParser is added to the project:
`var pos = Console.GetCursorPosition();`

I would recommend closing this issue @embix .

I think you may find help on this error here:

[https://github.com/dotnet/runtime/issues/28625](url)
[https://stackoverflow.com/questions/20492535/system-io-ioexception-when-calling-system-console-windowwidth](url)

**Comment by embix** [comment]
You're absolutely right, the error is coming from `System.Console` and not any fancy extension method. How did I not see this?!
